name: Update README with Commit Count

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit count
        id: commit_count
        run: |
          COMMIT_COUNT=$(curl -s "https://api.github.com/users/SEU_USERNAME/events/public" | grep -c 'PushEvent')
          echo "::set-output name=commit_count::$COMMIT_COUNT"

      - name: Update README
        run: |
          sed -i "s/<!-- COMMIT_COUNT -->/<!-- COMMIT_COUNT -->${{ steps.commit_count.outputs.commit_count }}/g" README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update commit count in README"
          git push
